<table id="pending-housing-application">
  <caption><?php echo $this->escape($this->caption) ?></caption>
  <thead>
    <tr>
      <th>OSU ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Dining plan</th>
      <th>Building preferences</th>
      <th>Profile answers</th>
      <th>Rooommates</th>
      <th>Application completed at</th>
      <th>Facility booking</th>
      <th>Meal plan booking</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->rows as $row): ?>
    <tr>
      <td><a href="<?php echo $row['person_uri'] ?>"><?php echo $this->escape($row['osuid']) ?></a></td>
      <td><?php echo $this->escape($row['name']) ?></td>
      <td><?php echo $this->escape($row['age']) ?></td>
      <td><?php echo $this->escape($row['gender']) ?></td>
      <td><?php echo $this->escape($row['dining_plan']) ?></td>
      <td><?php echo nl2br($this->escape($row['preferences'])) ?></td>
      <td><?php echo $this->escape($row['profile']) ?></td>
      <td>
    <?php foreach ($row['roommates'] as $roommate): ?>
        <a href="<?php echo $roommate['uri'] ?>"><?php echo $this->escape($roommate['text']) ?></a><br>
    <?php endforeach ?>
      </td>
      <td><?php echo $this->markupDateTime($row['application_completed_at']) ?></td>
      <td><a href="<?php echo $this->escape($row['facility_booking_uri']) ?>">Book</a></td>
      <td><a href="<?php echo $this->escape($row['mealplan_booking_uri']) ?>">Book</a></td>
    </tr>
<?php endforeach ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#pending-housing-application').dataTable({
    aoColumnDefs: [
      { aTargets: [8], sType: 'time-html' },
    ],
    sDom: '<"H"fl>t<"F"ip>'
  });
});
</script>
