<table id="pending-into-application">
  <caption><?php echo $this->escape($this->caption) ?></caption>
  <thead>
    <tr>
      <th>OSU ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Reservation start</th>
      <th>Reservation end</th>
      <th>Booking start</th>
      <th>Booking end</th>
      <th>Smoker?</th>
      <th>Housing code</th>
      <th>Facility booking</th>
      <th>Meal plan booking</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->rows as $row): ?>
    <tr>
      <td><a href="<?php echo $row['person_uri'] ?>"><?php echo $this->escape($row['osuid']) ?></a></td>
      <td><?php echo $this->escape($row['name']) ?></td>
      <td><?php echo $this->escape($row['age']) ?></td>
      <td><?php echo $this->escape($row['gender']) ?></td>
      <td><?php echo $this->markupDate($row['reservation_start']) ?></td>
      <td><?php echo $this->markupDate($row['reservation_end']) ?></td>
      <td><?php echo $this->markupDate($row['booking_start']) ?></td>
      <td><?php echo $this->markupDate($row['booking_end']) ?></td>
      <td><?php echo $this->escape($row['is_smoker']) ?></td>
      <td><?php echo $this->escape($row['housing_code']) ?></td>
      <td><a href="<?php echo $this->escape($row['facility_booking_uri']) ?>">Book</a></td>
      <td><a href="<?php echo $this->escape($row['mealplan_booking_uri']) ?>">Book</a></td>
    </tr>
<?php endforeach ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#pending-into-application').dataTable({
    aoColumnDefs: [
      { sType: 'time-html', aTargets: [4, 5, 6, 7] }
    ],
    sDom: '<"H"if>t<"F"ip>'
  });
});
</script>
